### ISSUE TITLE
1 test failure: test_default_compile_command(TestRubyMode)

### ISSUE THREAD

**Issue by igravious** [shugo/textbringer#25]
```
==================================================================================
/home/groobiest/Code/textbringer/test/textbringer/modes/test_ruby_mode.rb:469:in `test_default_compile_command'
     466:   end
     467: 
     468:   def test_default_compile_command
  => 469:     Dir.mktmpdir do |dir|
     470:       pwd = Dir.pwd
     471:       Dir.chdir(dir)
     472:       begin
/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/home/groobiest/Code/textbringer/test/textbringer/modes/test_ruby_mode.rb:475:in `block in test_default_compile_command'
<"ruby2.3 /path/to/foo.rb"> expected but was
<"ruby /path/to/foo.rb">

diff:
? ruby2.3 /path/to/foo.rb
Failure: test_default_compile_command(TestRubyMode)
==================================================================================
```

Hi, I get this one error when I run the test suite with ```rake```.

**Comment by shugo** [comment]
@igravious Sorry for the delay.
Could you try the fix in 61adb8c?
